#!/usr/bin/env python3
"""Split ../index.html into the pieces the React app renders.

Stage 1 of the port: the live page is still the source of truth. Re-run this after
editing ../index.html while the port is staged (python3 scripts/port.py).
Everything lands in src/site/ and is generated; edit index.html, not these files.
"""
import re
from pathlib import Path

APP = Path(__file__).resolve().parent.parent
src = (APP.parent / "index.html").read_text(encoding="utf-8").split("\n")
OUT = APP / "src" / "site"
(OUT / "parts").mkdir(parents=True, exist_ok=True)

def lines(a, b):  # 1-indexed, inclusive
    return "\n".join(src[a - 1:b])

def find(prefix, start=1):
    for i in range(start - 1, len(src)):
        if src[i].startswith(prefix):
            return i + 1
    raise SystemExit("not found: " + prefix)

def absolute(text):
    """The app is served from /preview-react/, so site assets and demos need root-absolute paths."""
    return re.sub(r"""(["'`(])((?:assets|demos)/)""", r"\1/\2", text)

style_a, style_b = find("<style>"), find("</style>")
css = lines(style_a + 1, style_b - 1)
(OUT / "site.css").write_text(absolute(css), encoding="utf-8")

hero_a, reel_a = find("<section class=\"hero\">"), find("<section id=\"reel\"")
proj_a = find("<!-- ============================= MISSION MODEL")
about_a = find("<section class=\"about\"")
contact_a = find("<section class=\"resume-band\"")
main_end = find("</main>")
parts = {
    "reel": (reel_a, proj_a - 1),
    "projects": (proj_a, about_a - 1),
    "about": (about_a, contact_a - 1),
}
import json

for name, (a, b) in parts.items():
    text = absolute(lines(a, b))
    if name == "reel":
        text = text.replace('<section id="reel" aria-labelledby="projects-title">', '<section id="reel-src" hidden aria-hidden="true">', 1)
        assert "reel-src" in text
    if name == "projects":
        # one entry per write-up: the head, then one panel per sub-heading (Overview, Method, Outcome...)
        out = []
        for m in re.finditer(r'<section class="project-section" id="([^"]+)">(.*?)\n</section>', text, re.S):
            parts_ = re.split(r'<h3 class="subhead"[^>]*>(.*?)</h3>', m.group(2))
            out.append({"id": m.group(1), "head": parts_[0].strip(),
                        "tabs": [{"label": re.sub("<[^>]+>", "", parts_[i]), "html": parts_[i + 1].strip()} for i in range(1, len(parts_), 2)]})
        assert len(out) == text.count('class="project-section"'), (len(out), text.count('class="project-section"'))
        (OUT / "projects.json").write_text(json.dumps(out, ensure_ascii=False), encoding="utf-8")
        continue
    (OUT / "parts" / f"{name}.html").write_text(text + "\n", encoding="utf-8")

# The page script, wrapped so React can run it once the markup exists.
sc_a = find("<script>", find("</footer>"))
sc_b = find("</script>", sc_a)
body = absolute(lines(sc_a + 1, sc_b - 1))
# project-card thumbnails are decorative, same as the reel's: they carry no chart labels
THUMB = 'el.closest(".frame")'
assert body.count(THUMB) == 1
body = body.replace(THUMB, 'el.closest(".frame, .rc-media")')
SEL = "#reel a[href^='#']"
assert body.count(SEL) == 1
body = body.replace(SEL, "#reel-src a[href^='#']")  # the React reel replaces #reel; the original stays hidden as data
(OUT / "legacy.js").write_text(
    "// @ts-nocheck\n// Generated by scripts/port.py from ../index.html. Do not edit.\n"
    "export function initLegacy() {\n" + body + "\n}\n", encoding="utf-8")
(OUT / "legacy.d.ts").write_text("export function initLegacy(): void\n", encoding="utf-8")
print("ported:", {p.name: p.stat().st_size for p in sorted(OUT.rglob("*")) if p.is_file()})
