#!/usr/bin/env python3
"""Split ../index.html into the pieces the React app renders.

Stage 1 of the port: the live page is still the source of truth. Re-run this after
editing ../index.html while the port is staged (python3 scripts/port.py).
Everything lands in src/site/ and is generated; edit index.html, not these files.
"""
import re
from pathlib import Path

APP = Path(__file__).resolve().parent.parent
src = (APP.parent / "index.html").read_text(encoding="utf-8").split("\n")
OUT = APP / "src" / "site"
(OUT / "parts").mkdir(parents=True, exist_ok=True)

def lines(a, b):  # 1-indexed, inclusive
    return "\n".join(src[a - 1:b])

def find(prefix, start=1):
    for i in range(start - 1, len(src)):
        if src[i].startswith(prefix):
            return i + 1
    raise SystemExit("not found: " + prefix)

def absolute(text):
    """The app is served from /preview-react/, so site assets and demos need root-absolute paths."""
    return re.sub(r"""(["'`(])((?:assets|demos)/)""", r"\1/\2", text)

style_a, style_b = find("<style>"), find("</style>")
css = lines(style_a + 1, style_b - 1)
(OUT / "site.css").write_text(absolute(css), encoding="utf-8")

hero_a, reel_a = find("<section class=\"hero\">"), find("<section id=\"reel\"")
proj_a = find("<!-- ============================= MISSION MODEL")
about_a = find("<section class=\"about\"")
contact_a = find("<section class=\"resume-band\"")
main_end = find("</main>")
parts = {
    "reel": (reel_a, proj_a - 1),
    "projects": (proj_a, about_a - 1),
    "about": (about_a, contact_a - 1),
}
for name, (a, b) in parts.items():
    (OUT / "parts" / f"{name}.html").write_text(absolute(lines(a, b)) + "\n", encoding="utf-8")

# The page script, wrapped so React can run it once the markup exists.
sc_a = find("<script>", find("</footer>"))
sc_b = find("</script>", sc_a)
body = absolute(lines(sc_a + 1, sc_b - 1))
(OUT / "legacy.js").write_text(
    "// @ts-nocheck\n// Generated by scripts/port.py from ../index.html. Do not edit.\n"
    "export function initLegacy() {\n" + body + "\n}\n", encoding="utf-8")
(OUT / "legacy.d.ts").write_text("export function initLegacy(): void\n", encoding="utf-8")
print("ported:", {p.name: p.stat().st_size for p in sorted(OUT.rglob("*")) if p.is_file()})
